# Generated by Django 5.2.1 on 2025-06-07 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_populate_categories_and_fix_models'),
        ('auctions', '0008_alter_listing_seller_alter_listing_starting_price'),
    ]

    operations = [
    ]
